### ISSUE TITLE
When I try to run a custom data set, he gets the following error

### ISSUE THREAD

**Issue by jiangzeshuo** [Lornatang/YOLOv3-PyTorch#2]
When I try to run a custom data set, he gets the following error
![image](https://user-images.githubusercontent.com/51223123/79866750-c9c63a80-83cc-11ea-9aa0-4043a4d09ebc.png)then i try name instead module_type but it stil erro

**Comment by Lornatang** [comment]
@jiangzeshuo This problem has been fixed in the new version. Please pull the latest code
