### ISSUE TITLE
CUDA out of memory!

### ISSUE THREAD

**Issue by JamesZhan107** [Lornatang/YOLOv3-PyTorch#3]
When i train custom data , It always gives this error. 
![image](https://user-images.githubusercontent.com/37035703/95551513-81174200-0a3d-11eb-8595-6ddc9b7a9bb0.png)

Are there any parameters I need to set ???

**Comment by JamesZhan107** [comment]
I solved this problem after add --image-size in train command! But the mAP is very low...

**Comment by JamesZhan107** [comment]
@Lornatang

**Comment by Lornatang** [comment]
I don't seem to have encountered this problem, and if there is not enough batch, there may be a problem loading the dataset.

**Comment by JamesZhan107** [comment]
> I don't seem to have encountered this problem, and if there is not enough batch, there may be a problem loading the dataset.

The mAP is still very low after i modify the batch-size to 64.

But when i trained on ultralytics/yolov3 , it works well.  @Lornatang

**Comment by JamesZhan107** [comment]
when i use your  mobilenetv3-large cfg file on ultralytics/yolov3, It produces the following error.

![image](https://user-images.githubusercontent.com/37035703/95669403-12f48b80-0bb3-11eb-9846-85bd6bd3a23c.png)

Is this a problem with the cfg file or what function needs to be modified？ @Lornatang 

I'm sorry to disturb you !

**Comment by Lornatang** [comment]
I didn't test enough on the mobilenetv3 large configuration file. Don't use it first

**Comment by JamesZhan107** [comment]
OK, there is no problem with v1 and v2. Mobilenetv3 large and small configuration file is something wrong.

**Comment by JamesZhan107** [comment]
OK, there is no problem with v1 and v2. Mobilenetv3 large and small configuration file has something wrong.
