### ISSUE TITLE
May I know how to generate confusion matrix?

### ISSUE THREAD

**Issue by Hrishkesh** [Lornatang/YOLOv3-PyTorch#4]
## 🚀 Feature
A clear and concise description of the feature proposal.

## Motivation & Examples

Tell us why the feature is useful.

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers --
we only consider papers that have enough significance and prevalance.

We do not take requests for most projects in the `projects/` directory,
because they are research code release that is mainly for other researchers to reproduce results.

Instead of adding features inside easydet,

**Comment by Lornatang** [comment]
Please describe your problem in detail. What do you mainly use for.

**Comment by Hrishkesh** [comment]
@Lornatang I could generate mAP and IOU but, I need a matrix to visualize how many true positives are detected.
So I can have it in my final report of my master thesis.
for example in my case, I have three classes to detect from a single image.
such as company name, date, and amount from the invoice image.
Such that I can an overview of how many times the company name, date, and amount is been detected in the test/valid data set.

@Lornatang So, this would be helpful to view it in my report as this is needed for better understanding.

**Comment by Hrishkesh** [comment]
Hello @Lornatang, as it is a bit urgent may I know how to generate it?

**Comment by Lornatang** [comment]
I'm sorry, I'm busy at the moment. I can't help you at the moment
